CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS report_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id TEXT NOT NULL,
    frequency TEXT NOT NULL,
    emails TEXT NOT NULL,
    scheduled_hour INT DEFAULT 9,
    last_sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_schedule_combination UNIQUE (telegram_id, frequency, emails, scheduled_hour)
);

CREATE TABLE IF NOT EXISTS app_users (
    telegram_id TEXT PRIMARY KEY,
    username TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO categories (category_name) VALUES
('Groceries'), ('Transport'), ('Utilities'), ('Dining'),
('Shopping'), ('Rent'), ('Entertainment'), ('Medical'), ('Other')
ON CONFLICT (category_name) DO NOTHING;

CREATE OR REPLACE FUNCTION get_user_statistics(p_user_id text)
RETURNS TABLE (category_name text, total_spent numeric) AS $$
BEGIN
  RETURN QUERY
  SELECT COALESCE(c.category_name, 'Other')::text, SUM(t.amount)::numeric
  FROM transactions t
  LEFT JOIN categories c ON t.category_id = c.id
  WHERE t.user_id = p_user_id
  GROUP BY c.category_name
  ORDER BY SUM(t.amount) DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

ALTER TABLE transactions
ALTER COLUMN transaction_date TYPE DATE
USING transaction_date::DATE;

-- 1. Add the new text columns
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Other';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS subcategory TEXT DEFAULT 'General';

-- 2. Drop the old relational foreign key constraint
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_category_id_fkey;

-- 3. Drop the old category_id column
ALTER TABLE transactions DROP COLUMN IF EXISTS category_id;

-- 4. Delete the obsolete categories table entirely
DROP TABLE IF EXISTS categories CASCADE;

ALTER TABLE transactions RENAME COLUMN description TO item_name;