-- 1. Create the immutable audit table
CREATE TABLE IF NOT EXISTS transaction_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    user_id TEXT NOT NULL,
    action_type TEXT NOT NULL CHECK (action_type IN ('INSERT', 'DELETE')),
    record_state JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Secure the audit table (No one should be able to update or delete logs)
ALTER TABLE transaction_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service Role Can Insert Logs" ON transaction_audit_logs 
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Users Can Read Own Logs" ON transaction_audit_logs 
    FOR SELECT USING (auth.uid()::text = user_id);

-- 3. Create the Database Trigger Function
CREATE OR REPLACE FUNCTION audit_transaction_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO transaction_audit_logs (transaction_id, user_id, action_type, record_state)
        VALUES (OLD.id, OLD.user_id, 'DELETE', row_to_json(OLD)::jsonb);
        RETURN OLD;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO transaction_audit_logs (transaction_id, user_id, action_type, record_state)
        VALUES (NEW.id, NEW.user_id, 'INSERT', row_to_json(NEW)::jsonb);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Attach Trigger to the Transactions Table
DROP TRIGGER IF EXISTS transaction_audit_trigger ON transactions;
CREATE TRIGGER transaction_audit_trigger
AFTER INSERT OR DELETE ON transactions
FOR EACH ROW EXECUTE FUNCTION audit_transaction_changes();