import os
import logging
from datetime import timedelta
from supabase import create_client, Client
from core.models import TransactionRecord
from core.utils import get_ist_now, FinanceManagerException

logger = logging.getLogger(__name__)

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY) if SUPABASE_URL else None


def get_or_create_category(category_name: str) -> int:
    """Dynamically fetches or creates a new category generated by the AI."""
    cat_name = category_name.title().strip()
    if not cat_name:
        cat_name = "Other"

    try:
        # Check if category already exists
        res = supabase.table("categories").select("id").eq("category_name", cat_name).execute()
        if res.data:
            return res.data[0]['id']

        # If it doesn't exist, create it on the fly
        new_res = supabase.table("categories").insert({"category_name": cat_name}).execute()
        return new_res.data[0]['id']
    except Exception as e:
        logger.error(f"Failed to resolve category {cat_name}: {str(e)}")
        return 1  # Fallback to ID 1 if catastrophic failure


def get_last_category(description: str) -> str | None:
    try:
        res = supabase.table("transactions").select("categories(category_name)").eq("description",
                                                                                    description.title()).order(
            "created_at", desc=True).limit(1).execute()
        if res.data and res.data[0].get('categories'):
            return res.data[0]['categories']['category_name']
        return None
    except:
        return None


def check_duplicate(user_id: str, amount: float, description: str) -> bool:
    try:
        ten_sec_ago = (get_ist_now() - timedelta(seconds=10)).isoformat()
        res = supabase.table("transactions").select("id").eq("user_id", user_id).eq("amount", amount).eq("description",
                                                                                                         description.title()).gt(
            "created_at", ten_sec_ago).execute()
        return len(res.data) > 0
    except:
        return False


def save_transaction(record: TransactionRecord) -> bool:
    try:
        # Resolve the string category name to a database ID
        cat_id = get_or_create_category(record.category_name)

        data = {
            "user_id": record.user_id,
            "amount": record.amount,
            "category_id": cat_id,
            "description": record.description.title(),
            "transaction_date": record.transaction_date.isoformat(),
            "remarks": record.remarks
        }
        supabase.table("transactions").insert(data).execute()
        return True
    except Exception as e:
        raise FinanceManagerException("Database", f"Commit failed: {str(e)}", "Check Supabase.")


def get_user_stats(user_id: str) -> str:
    try:
        res = supabase.rpc("get_user_statistics", {"p_user_id": user_id}).execute()
        data = res.data
        if not data: return "No expenses logged."
        total = sum(float(row['total_spent']) for row in data)
        msg = f"💰 **Total Spent: ₹{total:,.2f}**\n\n**Breakdown:**\n"
        for row in data:
            msg += f"{row.get('category_name', 'Other')}: ₹{float(row.get('total_spent', 0)):,.2f}\n"
        return msg
    except:
        return "Failed to fetch stats."